-- CreateEnum
CREATE TYPE "TaskBlockReason" AS ENUM ('MISSING_DOCUMENT', 'WAITING_APPROVAL', 'WAITING_SUPPLIER', 'WAITING_CUSTOMER', 'WAITING_PAYMENT', 'MISSING_MATERIAL', 'TECHNICAL_ISSUE', 'SYSTEM_ISSUE', 'PREVIOUS_TASK_INCOMPLETE', 'OTHER');

-- AlterEnum
ALTER TYPE "TaskStatus" ADD VALUE 'WAITING';

-- AlterTable
ALTER TABLE "Task" ADD COLUMN     "blockedNote" TEXT,
ADD COLUMN     "blockedReason" "TaskBlockReason";
